apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd-app
  namespace: ctfd
spec:
  replicas: 1
  selector:
    matchLabels:    
      app: ctfd-app
  template:
    metadata:
      labels:
        app: ctfd-app
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: ctfd-app
        image: deathfar/ctfd-app
        env:
        - name: ACCESS_LOG
          value: '-'
        - name: ERROR_LOG
          value: '-'
        - name: DATABASE_URL
          value: mysql+pymysql://ctfd:ctfd@10.96.225.96:3306/ctfd
        - name: REDIS_URL
          value: redis://10.96.192.114:6379
        - name: LOG_FOLDER
          value: /data/nfs
        - name: REVERSE_PROXY
          value: true
        - name: UPLOAD_FOLDER
          value: /data/nfs
        - name: WORKERS
          value: "1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: ctf-data
          mountPath: /data/nfs
      volumes:
      - name: ctf-data
        nfs:
          server: 158.160.111.226
          path: /data/nfs