apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctfd-ingress
  namespace: ctfd
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned"
    cert-manager.io/duration: 2160h
    cert-manaher.io/renew-before: 360h
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - myctfd.practice.ru
    secretName: myctfd-tls-secret
  rules:
  - host: myctfd.practice.ru
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ctfd-app
            port:
              number: 8000